version: "3.1"

services:
  loja:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: loja
    restart: always
    ports:
      - 8080:8080
    environment:
      - PROFILE=dev
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=loja
      - POSTGRES_PASSWORD=lojapw
      - POSTGRES_DB=lojadb