version: '3.0'

services:
  loja:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: loja_api
    ports:
      - '8080:8080'
    environment:
      - PROFILE=dev
    links:
      - db_loja
    depends_on:
      - db_loja
  db_loja:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./volume/volume_mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_loja
      - MYSQL_USER=db_bicycleshop_user
      - MYSQL_PASSWORD=db_bicycleshop_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
