version: "3.1"

services:
  loja:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: loja
    container_name: loja
    restart: always
    ports:
      - 8080:8080
    environment:
      - PROFILE=dev
    depends_on:
      - loja_db
      - eureka-server
    links:
      - loja_db
      - eureka-server
  fornecedor:
    build:
      context: ../fornecedor
      dockerfile: ./Dockerfile
    container_name: fornecedor
    restart: always
    ports:
      - 8081:8081
    environment:
      - PROFILE=dev
    depends_on:
      - fornecedor_db
  loja_db:
    image: postgres
    container_name: loja_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=loja
      - POSTGRES_PASSWORD=lojapw
      - POSTGRES_DB=lojadb
  fornecedor_db:
    image: postgres
    container_name: fornecedor_db
    restart: always
    ports:
    - 5433:5432
    environment:
      - POSTGRES_USER=fornecedor
      - POSTGRES_PASSWORD=fornecedorpw
      - POSTGRES_DB=fornecedordb

  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: always
    ports:
    - 8761:8761