spring:
  profile: dev
  application:
    name: loja
  datasource:
    url: jdbc:postgresql://localhost:5432/lojadb
    username: loja
    password: lojapw
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true






