server:
  port: 8080

spring:
  profile: dev
  application:
    name: loja
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://loja_db:5432/lojadb
    username: loja
    password: lojapw
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/








