spring:
  profile: qa
  application:
    name: bicycleshop
  datasource:
    url: jdbc:mysql://db_loja:3306/db_loja
    driverClassName: com.mysql.cj.jdbc.Driver
    username: db_bicycleshop_user
    password: db_bicycleshop_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        show-sql: true

